### ISSUE TITLE
App crashes when trying to access challenges 12 & 13

### ISSUE THREAD

**Issue by tahersb** [payatu/diva-android#3]
AndroidRuntime  E  FATAL EXCEPTION: main
                        E  Process: jakhar.aseem.diva, PID: 1155
                        E  java.lang.UnsatisfiedLinkError: Couldn't load divajni from loader dalvik.system.PathClassLoader[DexPathList[[zip fi
                           le "/data/app/jakhar.aseem.diva-1.apk"],nativeLibraryDirectories=[/data/app-lib/jakhar.aseem.diva-1, /system/lib]]]
                           : findLibrary returned null
                        E      at java.lang.Runtime.loadLibrary(Runtime.java:358)
                        E      at java.lang.System.loadLibrary(System.java:526)
                        E      at jakhar.aseem.diva.DivaJni.<clinit>(DivaJni.java:43)
                        E      at jakhar.aseem.diva.InputValidation3Activity.onCreate(InputValidation3Activity.java:49)
                        E      at android.app.Activity.performCreate(Activity.java:5231)
                        E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                        E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                        E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                        E      at android.app.ActivityThread.access$800(ActivityThread.java:135)
                        E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                        E      at android.os.Handler.dispatchMessage(Handler.java:102)
                        E      at android.os.Looper.loop(Looper.java:136)
                        E      at android.app.ActivityThread.main(ActivityThread.java:5001)
                        E      at java.lang.reflect.Method.invokeNative(Native Method)
                        E      at java.lang.reflect.Method.invoke(Method.java:515)
                        E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                        E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                        E      at dalvik.system.NativeStart.main(Native Method)

```
                       Process 1155 ended
```

<img width="1195" alt="screen shot 2016-09-20 at 2 53 05 am" src="https://cloud.githubusercontent.com/assets/8819446/18649506/6884d67a-7edd-11e6-8448-0082ec9d6a37.png">

**Comment by jehy** [comment]
native library was not found - did you compile it?

**Comment by z3dc0ps** [comment]
watch this video to clear all doubts: https://www.youtube.com/watch?v=PXvEh_QhGt8
